version: '3.4'

services:
  webjournal:
    container_name: "Web_Api"
    image: ${DOCKER_REGISTRY-}webjournal
    build:
      context: .
      dockerfile: FirstWebAPI/Dockerfile
    depends_on:
      - postgres
    ports:
      - "443:443"
    
  postgres:
    container_name: "postgresDB"
    image: postgres:15.3
    environment:
      POSTGRES_DB: DenisDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 301600
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8000:80"
    networks:
      - postgres

  client:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend_c
    stdin_open: true
    tty: true

networks:
  postgres:
    driver: bridge